"""User relationship added with Project

Revision ID: 3a9aadcea3bd
Revises: 95488e751efd
Create Date: 2026-01-02 13:06:31.903543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a9aadcea3bd'
down_revision: Union[str, None] = '95488e751efd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'project_members', ['project_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_members', type_='unique')
    # ### end Alembic commands ###
