"""rename project name to title

Revision ID: 484b611e2171
Revises: 32a893a9066f
Create Date: 2025-12-30 16:09:57.711832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '484b611e2171'
down_revision: Union[str, None] = '32a893a9066f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('projects', sa.Column('description', sa.String(length=290), nullable=True))
    op.drop_column('projects', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('projects', 'description')
    op.drop_column('projects', 'title')
    # ### end Alembic commands ###
